### ISSUE TITLE
Define 'physical origin'

### ISSUE THREAD

**Issue by metromoxie** [w3c/webappsec-suborigins#17]
It appears that we're going with the term 'physical origin' to define the traditional scheme/host/port tuple. We should formalize that in the spec somewhere.

**Comment by annevk** [comment]
If the definition of origin is going to be changed that should probably happen in HTML. It currently defines three types of origins: opaque identifiers, tuples, and aliases.

**Comment by metromoxie** [comment]
For reference:
https://www.w3.org/TR/html5/browsers.html#origin
https://html.spec.whatwg.org/multipage/browsers.html#origin

True enough, or we can try to define it in terms of the "additional data"/"extra data" in the tuple. That might be the simplest way to start.

But even if we want to extend the Tuple origin definition, it might make sense to start here, come to consensus, and bring it to the HTML spec.

**Comment by annevk** [comment]
Fair.

**Comment by metromoxie** [comment]
Physical origin was defined in #57, so closing.
