### ISSUE TITLE
Suborigin header should only use the last header, not any of the first ones

### ISSUE THREAD

**Issue by metromoxie** [w3c/webappsec-suborigins#19]
I believe other headers just take the "last" one, and certainly that's how Chrome is setup to operate, so we should probably reword the spec to specify that the *last* Suborigin header specified is the winner, rather than the first one.

**Comment by metromoxie** [comment]
I've changed my mind :-) I misunderstood the Chrome code, and I think it would be more consistent with other specs to only take the first, so I think we should close #20 without committing. What do you think?

**Comment by devd** [comment]
Sgtm
