### ISSUE TITLE
Unsafe Opt-outs for postMessage

### ISSUE THREAD

**Issue by devd** [w3c/webappsec-suborigins#24]
Currently, suborigins makes it hard to be a drop in replacement in cases where the rest of the world knows only about your old origin. We should have an 'unsafePostMessage'  primitive. 

This will have two effects:

Currently: 
Suborigin foo @ example.com
event.origin ==  https://foo_example.com/
event.suborigin = "foo"

With the opt-out, the message event will have
```
event.origin ="https://example.com"
event.suborigin = "foo"
```

We still include suborigin if you want to use it to check who the message should come from. Second, for messages sent to the suborigin, it will get messages for https://example.com. But, note that the sender can just send to https://foo_example.com to make sure it only gets to the suborigin. This is symmetrical to how event.suborigin still exists in the postMessage event above.

**Comment by metromoxie** [comment]
We started addressing this in #31.

**Comment by metromoxie** [comment]
I think this should be closed since we pretty much figured out "what" we're doing in #31, although it needs cleanup and precision, so I'm closing this. @devd, if you feel that we're fundamentally missing something, feel free to reopen.
