### ISSUE TITLE
postMessage extra argument for suborigin

### ISSUE THREAD

**Issue by devd** [w3c/webappsec-suborigins#26]
Right now, sending a message to a suborigin is not easily backwards compatible. We should allow sending a postMessage with a suborigin value in the 4th argument. So,

```
postMessage("message","https://www.example.com",null,"foo")
```

will send to https://www.example.com in old browsers; only to https://foo_www.example.com on browsers support suborigins.

**Comment by annevk** [comment]
I think it would be better if you could detect suborigin support somehow and branch on that if you wanted to support older browsers.

1. That seems more secure since by default you'll fail to communicate.
2. That will keep `postMessage()` a somewhat sane method call. I don't think four arguments is acceptable.

**Comment by devd** [comment]
yeah, iirc, when we were hashing this out @metromoxie and I felt that people would push back against feature detection like that in the client side. @metromoxie what do you think?

**Comment by metromoxie** [comment]
We should probably have client side feature detection anyway, as I suspect there are probably many other uses. But in addition, our thought was that it would be easier for developers to use postMessage with suborigins directly.

**Comment by annevk** [comment]
But long term when all browsers support suborigins, it will be more easy to do the wrong thing. We should design the API for the long term, not early adopters.

**Comment by metromoxie** [comment]
I think that's a good point. And this is something that a decent library could wrap pretty easily, if we have good feature detection, right?

**Comment by annevk** [comment]
Yes it could.

**Comment by devd** [comment]
I am closing this out because of the latest changes to postMessage by @jeisinger address this IMO
