### ISSUE TITLE
Behavior of Host prefix in the presence of unsafe-cookies option

### ISSUE THREAD

**Issue by devd** [w3c/webappsec-suborigins#28]
We need to define an optout which removes the suborigins separate cookie jar and ties the cookie jar (both from set-cookie header and the document.cookie API) to the physical origin.

One question is what we want to do with **Host** prefixed cookies.

**Comment by metromoxie** [comment]
We started addressing this in #31.

**Comment by metromoxie** [comment]
I think we figured out most of the issues in #31, but the Host prefix question is still a good one, so I'm going to rename this issue to reflect that in particular.

Personally, I think the `unsafe-cookies` option is, well, unsafe, and for simplicity's sake, we should just straight treat the suborigin as the physical origin in all ways when it comes to cookies, thus the Host prefix would treat the suborigin as same-origin. Thoughts?

**Comment by devd** [comment]
Sgtm.. if we decide that better control is needed, we can create a new flag
in future versions of the spec. Keeping it simple here is worthwhile.

**Comment by devd** [comment]
closing per above .. unsafe cookies flag is unsafe. #yolo
