### ISSUE TITLE
Suborigin names should not be allowed to start with number

### ISSUE THREAD

**Issue by metromoxie** [w3c/webappsec-suborigins#47]
At the very least, suborigin names should not be allowed to be a pure number, as in the serialization this could easily lead to parsing bugs that confuse the suborigin name with an IP literal. It's probably sufficient to just ban starting with a number, although perhaps we should outright disallow numerals.

**Comment by annevk** [comment]
Maybe we should instead figure out what is absolutely safe in all the various contexts and use that? E.g., lowercase a-z?

**Comment by devd** [comment]
I like the lowercase a-z idea. It also gives us ability to namespace later via upper case / numbers (for #40 )

**Comment by lgierth** [comment]
a-z would break our current usage of suborigin in IPFS, where we use multihashes as suborigin names to isolate e.g. /ipfs/Qmfoo from /ipfs/Qmbar. I suppose we could encode the hashes with a-z only, but that's less ideal than base32.

> It's probably sufficient to just ban starting with a number, although perhaps we should outright disallow numerals.

Both of these would work for go-ipfs :+1:

**Comment by devd** [comment]
closed per above merge
