### ISSUE TITLE
Don't use The Web Origin Concept

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-suborigins#53]
That specification is mostly an informative guide at this point. If you actually want to change what an origin is, you need to patch HTML.

(I realize you told me not to review, but couldn't help but notice this while looking at the Fetch changes.)

**Comment by devd** [comment]
Not https://tools.ietf.org/html/rfc6454 ?

**Comment by annevk** [comment]
Right. See how HTML deals with origins.

**Comment by metromoxie** [comment]
Will do! Thanks for the issue.

**Comment by metromoxie** [comment]
All normative references are removed. Where origin updates are necessary, we've started using origin in HTML.
