### ISSUE TITLE
Why having both serialized origins and finerorigin/suborigin

### ISSUE THREAD

**Issue by mitar** [w3c/webappsec-suborigins#6]
I think introducing `finerorigin` and `suborigin` in `postMessage` events (and elsewhere) is problematic because it means that all apps now have to make a special case for when they are using suborigins and check those fields instead of `origin`. I think this adds unnecessary complexity to codepaths. If the main motivation why this is done is to:

> legacy applications should by default treat these messages as not coming from the traditional origin of the sender.

That is achieved already by just serializing the suborigin and setting the origin to that serialized string. It would not match the original origin anyway.

If one has to use origin value, one has to already parse it (into scheme, host, port). So having to parse it into scheme, host, port, suborigin is not so much more complexity. Also, in most cases you want to use origin as an opaque string anyway.

cc @wh0

**Comment by devd** [comment]
At the same time, I don't see the cost of having both if browser vendors are willing to implement it?

**Comment by devd** [comment]
closed by changes to PostMessage in latest push
