### ISSUE TITLE
Allow . in the suborigin

### ISSUE THREAD

**Issue by mitar** [w3c/webappsec-suborigins#8]
In RFC 3986, scheme is defined as:

```
scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

I would thus suggest that the suborigin is defined as:

```
ALPHA *( ALPHA / DIGIT / "-" / "." )
```

There is no reason to drop `.` from allowed characters.

**Comment by mitar** [comment]
cc @wh0

**Comment by devd** [comment]
we aren't putting the suborigin in the schema anymore, so this doesn't really apply directly
