### ISSUE TITLE
Are suborigins case sensitive or not?

### ISSUE THREAD

**Issue by mitar** [w3c/webappsec-suborigins#9]
In RFC 3986, scheme is defined as:

> Although schemes are case-insensitive, the canonical form is lowercase and documents that specify schemes must do so with lowercase letters.

So I would suggest suborigins are the same. So case-insensitive.

cc @wh0

**Comment by annevk** [comment]
Seems better to require them to be lowercase if they are also communicated via other means. That way comparisons are easier. That you can still write them using uppercase letters in URLs doesn't really impact that.

**Comment by mitar** [comment]
I do not have strong preference here, but I do think it should be clearly stated in the standard, this way or another.

**Comment by devd** [comment]
yeah, we will update the spec to say lower case only

**Comment by devd** [comment]
fixed by #22
